### PR TITLE
Feature/retry mechanism

### PR DESCRIPTION
**Pull request by cecemel**
Included an optional and configurable retry mechanism.

Sometimes, execution of queries may fail for technical
reasons, often related to the stack getting overloaded. In these cases,
it might make sense to just wait a little and retry again.

The conditions for retry are narrowly defined, by default, but may be configured at run time.
The type of conditions for retry are now connection errors and some httpErrors. These could expand over time.

### CODE REVIEW

**Comment by nbittich** [comment]
nice!

**Review by nvdk — COMMENTED** [review]
do chances of having queries running out of order increase when doing this? I need to think about this a bit more...

**Comment by cecemel** [comment]
@nvdk yes agree, although you are never sure of order. 
After your remark, I would suggest another approach: the caller needs the explicitly set for the query to be retried or not. So I least the client knows this. (We could keep the service wide setting though)

**Review by nvdk — APPROVED** [review]

**Comment by madnificent** [comment]
This is cool!  I'm a bit conflicted by this having both the retry option and the not retry option in the same service.  It feels a bit confusing to have the environment variables, as well as the source-code specification.  Perhaps we're making things harder on the consumer by making everything possible?

In other words: what is the motivation to disable retry in a service where we have previously enabled it?

I'd like to request a few updates:

- [ ] Add REAMDE documentation for new environment variables (`SUDO_QUERY_RETRY` and `SUDO_QUERY_RETRY_MAX_ATTEMPTS`)
- [ ] Make the timeout configurable (any sort of tweakable number is cool)
- [ ] Explicit in source-code that the environment variables `SUDO_QUERY_RETRY_FOR_HTTP_STATUS_CODES` and `SUDO_QUERY_RETRY_FOR_CONNECTION_ERRORS` are considered internal, but could be overridden by users as a temporary workaround for issues
- [ ] Perhaps not allow for overriding retry, depending on input from others

Note, I did not run this code, I only checked the diff.

**Comment by cecemel** [comment]
I agree about the potential source of conflict for overriding the retry service wide. 
I can imagine in some cases, you just want to enable service wide retry, without having to change the source code. I think you could argue that with this configuration setting enabled, you should be in 'know what you're doing space'.

**Comment by nvdk** [comment]
@madnificent  with @cecemel's changes I think this can be merged?

**Comment by nvdk** [comment]
having played with this a bit more: it's a bit weird that extraHeaders is not part of connectionOptions param. I guess this was kept for backwards compatibility?

**Comment by cecemel** [comment]
yeah, perhaps a next (major) release?

**Pull request merged**
